# Generated by Django 2.2 on 2019-04-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='decrypted_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='encrypted_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='key',
        ),
    ]
