# Generated by Django 2.2 on 2019-04-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190413_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plainText', models.TextField()),
                ('encryptedText', models.TextField(null=True)),
                ('decryptedText', models.TextField(null=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
